version: '3.7'
services:
  scrauso:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - storage
    environment:
      TERM: linux
      TERMINFO: /etc/terminfo
networks:
  storage:
    external: true
